name: "pre-release"

on:
  push:
    branches:
      - "master"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "windows-latest"
    
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build

        
      - name: Files
        run : |
          mkdir release;
          
          mkdir release/ChipThief;
          cp -r ChipThief\bin\Debug\net8.0\* release/ChipThief/;
          
          mkdir release/LuckyWheel;
          cp -r LuckyWheel\bin\Debug\net8.0\* release/LuckyWheel/;

          mkdir release/FerkOffCow;
          cp -r FerkOffCow\bin\Debug\net8.0\* release/FerkOffCow/;

          mkdir release/WelcomeToTheClubBuddy;
          cp -r WelcomeToTheClubBuddy\bin\Debug\net8.0-windows\* release/WelcomeToTheClubBuddy/;

          mkdir release/YoungMinecrafter;
          cp -r YoungMinecrafter\bin\Debug\net8.0-windows\* release/YoungMinecrafter/;
          
      - name: Zip
        uses: vimtor/action-zip@v1.2
        with:
          files: release/
          recursive: true
          dest: result.zip
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.TOKEN }}"
          automatic_release_tag: "Release"
          prerelease: true
          title: "Release"
          files: |
            result.zip
          
