name: "pre-release"

on:
  push:
    branches:
      - "master"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "windows-latest"
    
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build
      - name: Files
        run : |
          echo "$PWD"
          mkdir release
          echo "$PWD"
          ls
          mkdir release/ChipThief
          echo "$PWD"
          cp ChipThief/* /release/ChipThief
          ls
      - name: Zip
        uses: vimtor/action-zip@v1.2
        with:
          files: release/
          recursive: true
          dest: result.zip
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            result.zip
          
