name: "pre-release"

on:
  push:
    branches:
      - "master"

jobs:
  pre-release:
    name: "Pre Release"
    runs-on: "windows-latest"
    
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build

        
      - name: Files
        run : |
          mkdir release;
          mkdir release/ChipThief;
          pwd;
          cp ChipThief/* release/ChipThief/;
          echo "1"
          ls ChipThief
          echo "2"
          ls ChipThief/bin
          echo "3"
          ls ChipThief/bin/Debug
          echo "4"
          ls ChipThief/bin/Debug/net8.0
          
          
      - name: Zip
        uses: vimtor/action-zip@v1.2
        with:
          files: release/
          recursive: true
          dest: result.zip
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            result.zip
          
